### ISSUE TITLE
Manually pressing "Check" next to CheckQueue results in error

### ISSUE THREAD

**Issue by ovizii** [nzbgetcom/Extension-Completion#6]
I am running nzbget Currently installed: 24.1 via docker. 
I recently added and turned on this extension and since then all my downloads were paused. 

Searching for the problem, I realized that pressing “Check” next to CheckQueue results in an error. 

Any ideas?

```
Executing script Completion with command CheckQueue
Completion: Traceback (most recent call last):
Completion:   File "/usr/lib/python3.11/http/client.py", line 901, in _get_hostport
Completion:     port = int(host[i+1:])
Completion:            ^^^^^^^^^^^^^^^
Completion: ValueError: invalid literal for int() with base 10: 'Ju2Gnnd'
Completion: During handling of the above exception, another exception occurred:
Completion: Traceback (most recent call last):
Completion:   File "/mnt/downloads/scripts/Completion/main.py", line 1998, in <module>
Completion:     main()
Completion:   File "/mnt/downloads/scripts/Completion/main.py", line 1976, in main
Completion:     scheduler_call()
Completion:   File "/mnt/downloads/scripts/Completion/main.py", line 1817, in scheduler_call
Completion:     if not lock_file():  # check if script is not already running
Completion:            ^^^^^^^^^^^
Completion:   File "/mnt/downloads/scripts/Completion/main.py", line 1543, in lock_file
Completion:     nzbget_status = NZBGet.status()  # Get NZB status info XML-RPC
Completion:                     ^^^^^^^^^^^^^^^
Completion:   File "/usr/lib/python3.11/xmlrpc/client.py", line 1122, in __call__
Completion:     return self.__send(self.__name, args)
Completion:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Completion:   File "/usr/lib/python3.11/xmlrpc/client.py", line 1464, in __request
Completion:     response = self.__transport.request(
Completion:                ^^^^^^^^^^^^^^^^^^^^^^^^^
Completion:   File "/usr/lib/python3.11/xmlrpc/client.py", line 1166, in request
Completion:     return self.single_request(host, handler, request_body, verbose)
Completion:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Completion:   File "/usr/lib/python3.11/xmlrpc/client.py", line 1178, in single_request
Completion:     http_conn = self.send_request(host, handler, request_body, verbose)
Completion:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Completion:   File "/usr/lib/python3.11/xmlrpc/client.py", line 1279, in send_request
Completion:     connection = self.make_connection(host)
Completion:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
Completion:   File "/usr/lib/python3.11/xmlrpc/client.py", line 1256, in make_connection
Completion:     self._connection = host, http.client.HTTPConnection(chost)
Completion:                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Completion:   File "/usr/lib/python3.11/http/client.py", line 863, in __init__
Completion:     (self.host, self.port) = self._get_hostport(host, port)
Completion:                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Completion:   File "/usr/lib/python3.11/http/client.py", line 906, in _get_hostport
Completion:     raise InvalidURL("nonnumeric port: '%s'" % host[i+1:])
Completion: http.client.InvalidURL: nonnumeric port: 'Ju2Gnnd'
Script Completion with command CheckQueue failed (terminated with unknown status)
```

**Comment by luckedea** [comment]
@ovizii Sorry for slow response on this. The error shows that port is not correct, and it looks like a password in the port field. Can you confirm you still experiencing this problem? I wasn't able to replicate it. However if it was your configuration, then the downloads wouldn't have worked.

Need confirmation of the problem and more details about your configuration if possible please.

**Comment by ovizii** [comment]
Good catch. I can't verify that as I am busy moving to new hardware. Will close the issue for now, might reopen when I am done and can check again.
